title: Seth Miller
description: Personal site of Seth Miller
url: "https://four43.com"
baseurl: ""

theme: minima

markdown: kramdown
permalink: /:title/

exclude:
  - docs/
  - LICENSE
  - README.md
  - .obsidian/
  - Gemfile
  - Gemfile.lock
